### ISSUE TITLE
.git directory is published on composer

### ISSUE THREAD

**Issue by h3xx** [besanek/laravel-firebase-notifications#1]
There's some stuff published in the composer repo that shouldn't be there.

**Comment by besanek** [comment]
I think this is because only the development version is available that downloads as a source.
I have now released a new tag. Please update the package version to "~ 1.0" and run `composer update --prefer-dist besanek/laravel-firebase-notifications`

**Comment by h3xx** [comment]
Yes, I figured this out shortly after creating this issue.

What also works is deleting the vendor directory and running `composer install` again which loads from the cache. Weird.
